### ISSUE TITLE
Installation issues with latest react native

### ISSUE THREAD

**Issue by marksyzm** [ianprime0509/pitchy#107]
In react native using M1 and , I get a weird export issue as follows:

```
~/Sites/scratch/fortune2 » npm start 

> fortune@0.0.1 start /Users/****/Sites/scratch/fortune2
> react-native start

error Failed to load configuration of your project.
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/****/Sites/scratch/fortune2/node_modules/pitchy/package.json
    at new NodeError (node:internal/errors:377:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
    at resolveExports (node:internal/modules/cjs/loader:483:36)
    at Module._findPath (node:internal/modules/cjs/loader:523:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at resolveNodeModuleDir (/Users/****/Sites/scratch/fortune2/node_modules/@react-native-community/cli-tools/build/resolveNodeModuleDir.js:24:42)
    at /Users/****/Sites/scratch/fortune2/node_modules/@react-native-community/cli-config/build/loadConfig.js:93:76
    at Array.reduce (<anonymous>)
```

Any ideas what would cause it on this set up? I've got node v16

**Comment by ianprime0509** [comment]
Thanks for pointing this out! Apparently this is a common issue encountered by other projects using the `exports` field in package.json: https://github.com/uuidjs/uuid/issues/444

The fix was merged in #108 and is present in version 4.0.6.

**Comment by marksyzm** [comment]
@ianprime0509 perfect! Thanks so much

**Comment by marksyzm** [comment]
> Thanks for pointing this out! Apparently this is a common issue encountered by other projects using the `exports` field in package.json: https://github.com/uuidjs/uuid/issues/444
Cool! I couldn't work out what the exact fix was but I knew it was simple

**Comment by marksyzm** [comment]
Tested just now and I can confirm this works perfectly
